
CREATE TABLE callejero (
    id SERIAL PRIMARY KEY,
    seccion INT,
    tipo_via VARCHAR(50),
    nombre_calle VARCHAR(255),
    numero_inicio INT,
    numero_fin INT
);

INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'ABANDOLA', 2, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ABROTANO', 3, 37);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'ABUL CASIN BENEGAS', 1, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'ACEBUCHE', 2, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'ACEITUNEROS', 1, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ACEQUIA', 1, 24);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'ACEQUIA', 1, 24);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'ACEQUIA', 10, 24);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (4, 'CALLE', 'ACERA DE LA MARINA', 1, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'ACERA DE LA MARINA', 1, 24);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ACUARIO', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'ADEDOTO ALTAMIRANO', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ADEDOTO ALTAMIRANO', 2, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'ADOLFO PEREZ LOPEZ', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'AJOBLANCO', 1, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'AL ANDALUS', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'AL ANDALUS', 2, 22);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'PASAJE', 'AL ANDALUS', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'PASAJE', 'AL ANDALUS', 2, 22);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALBAHACA', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'ALBARDONEROS', 1, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'ALBARIÑO', 1, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'ALBATROS', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'ALBERO', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALBERQUILLA', 1, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALBERTO RUIZ GARCIA', 1, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'URB', 'ALBORAN', 1, 23);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'ALCALDE CAYETANO PASCUAL', 12, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'CALLE', 'ALCALDE DE RAMIRO MARCOS', 2, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'ALCALDE JOSE HERRERA', 3, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'CALLE', 'ALC. JUAN BARRANQUERO', 2, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'CALLE', 'ALCALDE MANUEL MARTEL', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'CALLE', 'ALC. MANUEL REINA REYNE', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'CALLE', 'ALCALDE ROMERO DE LA CRUZ', 3, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'CALLE', 'ALCALDE SANTIAGO VALLE', 4, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'CALLE', 'ALCALDE SANTIAGO VALLE', 3, 99);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'ALCALDE SANTIAGO VALLE', 48, 99);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALCANICLES', 1, 33);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALCANTARILLA', 1, 11);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALCAZABA', 1, 40);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'ALELLA', 1, 52);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALFAREROS', 1, 26);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALFEREZ ANTONIO GOMEZ', 1, 76);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'ALFONSO XII', 1, 76);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALFREDO KRAUS', 1, 26);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALHAMA DE GRANADA', 1, 49);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALHAMBRA', 2, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ALICANTE', 1, 15);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'ALMANSA', 3, 35);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'ALMARADI CONJUNTO', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'ALMAZARA', 1, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'ALMENA', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'ALMENDRO', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'ALOEVERA', 1, 59);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'ALPUJARRA', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'ALQUERIA', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'AMADEO TELLEZ', 3, 25);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'AMPURDAN', 1, 21);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'GLTA', 'ANCHA', 1, 36);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'AVDA', 'ANCLA', 1, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'ANDALUCIA', 1, 69);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'ANDALUCIA', 69, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'ANDALUCIA', 4, 56);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'ANDALUCIA', 32, 72);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'ANDALUCIA', 64, 99);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'ANDALUCIA', 71, 104);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'ANDALUCIA', 74, 109);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'ANDALUCIA', 101, 110);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'ANDALUCIA', 106, 169);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'ANDALUCIA', 151, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'ANDALUCIA', 1, 18);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'ANGEL', 1, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'ANGOSTA', 8, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'ANGUSTIAS', 3, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'ANGUSTIAS', 19, 26);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'ANGUSTIAS', 23, 24);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'ANGUSTIAS', 28, 25);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'ANGUSTIAS', 29, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'CALLE', 'ANTONIO DE LA CRUZ', 28, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'CALLE', 'ANTONIO GAMEZ BURGOS', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'CALLE', 'ANTONIO JIMENEZ', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'CALLE', 'ANTONIO MACHADO', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'AVDA', 'ANTONIO RUIZ QUERO', 1, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'AVDA', 'ANTONIO SALTO CARRION', 2, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'PLAZA', 'ANTOÑITA', 9, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'ANTONITA PLAZA', 2, 2);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'ANZUELO', 1, 2);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARBEQUIN', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'ARCIPRESTE JOSE ARIZA', 3, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'PLAZA', 'ARCO IRIS', 1, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARCO SAN PASCUAL', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'ARIES', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARQUITECTO FCO. ESTRADA', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'PASAJE', 'ARRIEROS', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO', 1, 24);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARROYO DE LA LOMILLA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO DE LA MOLINETA', 1, 37);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO DE LA MOLINETA', 3, 27);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO DE SAN FRANCISCO', 31, 37);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO DE SAN FRANCISCO', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO DE SAN FRANCISCO', 23, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARROYO HONDO', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARROYO HONDO', 3, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARROYO HONDO', 16, 45);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARROYO SAN SEBASTIAN', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'ARTEMISA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARTESANOS', 1, 26);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ATARAZANAS', 1, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'AURORA', 12, 18);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'PLAZA', 'AXARQUIA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'ANTONITA PLAZA', 2, 2);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'ANZUELO', 1, 2);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARBEQUIN', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'ARCIPRESTE JOSE ARIZA', 3, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'PLAZA', 'ARCO IRIS', 1, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARCO SAN PASCUAL', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'ARIES', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARQUITECTO FCO. ESTRADA', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'PASAJE', 'ARRIEROS', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO', 1, 24);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARROYO DE LA LOMILLA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO DE LA MOLINETA', 1, 37);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO DE LA MOLINETA', 3, 27);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO DE SAN FRANCISCO', 31, 37);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO DE SAN FRANCISCO', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'ARROYO DE SAN FRANCISCO', 23, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARROYO HONDO', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARROYO HONDO', 3, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARROYO HONDO', 16, 45);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARROYO SAN SEBASTIAN', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'ARTEMISA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ARTESANOS', 1, 26);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ATARAZANAS', 1, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'AURORA', 12, 18);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'PLAZA', 'AXARQUIA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'URB', 'AXARQUIA Y MAR', 26, 42);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'AZAHAR', 1, 37);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'AZALEA', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'AZOR', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'AZUCARERA', 1, 40);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'CALLE', 'AZUCARERA', 1, 49);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'AZUCARERA', 18, 42);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'AZUCENA', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'BAEZA', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'BAHIA', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'CALLE', 'BAHIA BLANCA', 1, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'BAJADA MOLINETA', 1, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'BAJADA DEL CERRO', 1, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'CALLE', 'BALANDRO', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'BALCONES DEL ROMERAL', 1, 40);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'BALLENERO', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'BAMBALINAS', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CALLE', 'BANANA', 1, 40);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'BARBACANA', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'BARCELONA BARRIO', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'BARLOVENTO', 1, 11);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'PASALE', 'BARQUERO', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'BARRACAS DE PONIENTE', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'BARRENDERO', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'BARRERO DE CAPUCHINOS', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'BATERIA', 1, 38);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'BEATAS', 3, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'BEATAS', 4, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'BEATAS', 6, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'BELLAVISTA', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'BENAVENTE', 2, 2);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'BENTOMIZ', 3, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CALLE', 'BERNABE FERNANDEZ', 3, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CALLE', 'BERNABE FERNANDEZ', 8, 15);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'BLAS INFANTE', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'BLAS INFANTE', 3, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'BLAS INFANTE', 12, 15);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'BOLINA', 6, 25);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'CALLE', 'BRISA DE LA VIÑA', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'BULERIA', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'BULERIA', 2, 15);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'BURGOS', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'CADIZ', 1, 13);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'CALAFATE', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'CALETA Y EL LIMONAR', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CALLEJON DE LOS PALACIOS', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CALLEJON DE PALACIOS', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CALZADA HERRERA', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CALZADILLA HERRERA', 1, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CAMARON', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CAMPILLO', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'PASALE', 'CANASTEROS', 1, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'CAMPO DE BORJA', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CAMPO REAL', 1, 35);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'CANALEJAS', 1, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'CANALEJAS', 1, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'CAÑADA DE LA MOLINETA', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CAÑADA DE LA MOLINETA', 11, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CAÑADU', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CAÑAVERAL', 1, 39);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CAÑON', 1, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CAPITAN', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CAPUCHINOS', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'CARACOLA', 1, 26);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CARBONERA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CARIÑENA', 2, 44);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CARLOS CANO', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'PASAJE', 'CARPINTEROS', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CARRASCO', 1, 34);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'CALLE', 'CASA DE LA VIÑA', 1, 40);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CASAS NUEVAS', 1, 39);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CASILLAS DE LA VIA', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'PLAZA', 'CATALANES', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'PLAZA', 'CATALANES', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'CERCADILLO DE SANTA MARIA', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'CERCADILLO DEL MORO', 1, 18);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'CERCADILLO SAN SEBASTIAN', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'CERRILLO', 1, 2);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'CERRO DEL AGUILA', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CERVANTES', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'CINGULO', 1, 31);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'CLARA CAMPOAMOR', 1, 25);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CLAUDIO COELLO', 1, 60);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CLAVEL', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CLAVEL', 1, 39);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'COBALTO', 1, 31);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'COBALTO', 5, 35);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'COBERTIZO OLMEDO', 1, 15);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'COFRADE ACOSTA NADALES', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'COMPAS', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CONCEPCION', 3, 11);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CONCEPCION', 11, 21);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'AVDA', 'CONDADO DE HUELVA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'AVDA', 'CONDADO DE HUELVA', 31, 31);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CONDE DE UTIEL', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'LUGAR', 'CONJUNTO ALBATROS', 3, 4);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'CONJUNTO DEL CARMEN', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CONJUNTO DON LUCIO', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CONJUNTO EL JARDIN', 11, 35);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'LUGAR', 'CONJUNTO ISLA DEL SOL', 1, 38);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'LUGAR', 'CONJUNTO LOS GERANEOS', 3, 78);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'LUGAR', 'CONJUNTO VILLA LOLA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'CONSISTORIAL', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'COOPERATIVA SAN VALENTIN', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'COPO', 34, 65);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'COPO', 1, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'CORDOBA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'CORREGIDOR DIEGO ARIAS', 1, 73);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'CRISTO DE LA COLUMNA', 1, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'CRISTO DE LOS VIGIAS', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'CRISTO DE MEDINACELI', 1, 2);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'CRISTO DEL CERRO', 5, 27);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'CRISTO HUMILDAD', 2, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'CRISTO RESUCITADO', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'CROMO', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CRUZ DEL CORDERO PLAZA', 1, 85);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'CRUZ VERDE', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'CUESTA CEBALLOS', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'CALLE', 'CUESTA DEL VISILLO', 2, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'PASEO', 'CUSTODIO PUGA', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'PASEO', 'DE LARIOS', 1, 38);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CMNO VJO', 'DE VELEZ MALAGA', 12, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CMNO VJO', 'DE VELEZ MALAGA', 13, 29);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CMNO VJO', 'DE VELEZ MALAGA', 23, 43);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'PASEO', 'DE ANDALUCIA', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'RONDA', 'DE ANDALUCIA', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CTRA', 'DE ARENAS', 1, 50);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'AVDA', 'DE CARLOS III', 1, 51);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'DE CARLOS III', 5, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'DE COLON', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'DE ENMEDIO', 21, 73);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'PLAZA', 'DE LA AXARQUIA', 1, 23);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'PLAZA', 'DE LA CONCEPCION', 1, 23);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'PLAZA', 'DE LA CONSTITUCION', 1, 23);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CAMINO', 'DE LA ESTACION', 1, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'DE LA IMAGEN', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'PLAZA', 'DE LA MURALLAS', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'PLAZA', 'DE LA OLA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DE LA PAZ', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'PLAZA', 'DE LA PAZ', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'DE LA VIÑA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'PLAZA', 'DE LAS CARMELITAS', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'PLAZA', 'DE LAS CARMELITAS', 6, 13);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'PLAZA', 'DE LAS CARMELITAS', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'PLAZA', 'DE LAS CARMELITAS', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'PLAZA', 'DE LAS INDIAS', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'DE LAS TIENDAS', 1, 68);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CTRA', 'DE LOJA', 4, 4);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'DE LOS GIGANTES', 1, 31);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DE LOS MOROS', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'PLAZA', 'DE LOS PALACIOS', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CAMINO', 'DE MALAGA', 1, 57);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CMNO VJO', 'DE MALAGA', 1, 38);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CMNO VJO', 'DE MALAGA', 1, 24);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CMNO VJO', 'DE MALAGA', 12, 47);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CMNO VJO', 'DE MALAGA', 29, 24);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'PLAZA', 'DE SAN FRANCISCO', 1, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'PLAZA', 'DE SAN ROQUE', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'TRAVESIA', 'DE SANTA CRUZ', 1, 11);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CION', 'DE SANTA MARIA', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'AVDA', 'DE SEGOVIA', 1, 34);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'AVDA', 'DE TOROS VIEJA', 1, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'AVDA', 'DE VIVAR TELLEZ', 1, 36);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'AVDA', 'DE VIVAR TELLEZ', 71, 73);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'AVDA', 'DE VIVAR TELLEZ', 34, 38);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'DEBLA', 2, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'DECANO ICAM J. A PELA', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DEL AGUA', 1, 11);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (4, 'CAMINO', 'DEL ALGARROBO', 6, 31);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (4, 'CAMINO', 'DEL ALGARROBO', 12, 38);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (4, 'CAMINO', 'DEL ALGARROBO', 33, 71);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (4, 'CAMINO', 'DEL ALGARROBO', 40, 46);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'PLAZA', 'DEL CARMEN', 1, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'Cjón', 'DEL CATALAN', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'Cjón', 'DEL CATALAN', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'PLAZA', 'DEL CIERRO', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'PLAZA', 'DEL ESPINAR', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CAMINO', 'DEL HIGUERAL', 1, 99);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'PASAJE', 'DEL INTERIOR', 1, 99);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DEL MAR', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'DEL MAR', 3, 22);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'DEL MAR', 17, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'DEL MAR', 22, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'DEL MAR', 28, 72);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'DEL MAR', 30, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'DEL POZANCON', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DEL RIO', 1, 46);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'TRAVESIA', 'DEL RIO', 1, 46);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'DEL RIO', 1, 46);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'DEL RIO', 1, 46);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'PASALE', 'DEL ROCIO', 1, 53);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'AVDA', 'DEL SOL', 3, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CJON', 'DEL TEJAR', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'PLAZA', 'DEL TRABAJO', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DEL VICARIO', 4, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'DESAMPARADOS', 2, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'AVDA', 'DESFILADERO D LOS GAITANES', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'DOCTOR FLEMING', 1, 15);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'DOCTOR FLEMING', 3, 25);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'DOCTOR FLEMING', 17, 25);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'DOCTOR FLEMING', 25, 65);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'DOCTOR FLEMING', 28, 48);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'DOCTOR FLEMING', 16, 34);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'DOCTOR JIMENEZ POEY', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DOCTOR JOSE CALLE CACERES', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DOCTOR MANUEL DEL PINO', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DOCTOR MARAÑON', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DOCTOR MARAÑON', 6, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'DOCTOR MARAÑON', 16, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'DOCTOR MARAÑON', 18, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'DOLORES GAMEZ RUIZ', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'DOMINGO HEREDIA', 3, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'PASAJE', 'DON FCO. DEL PINO ROLDAN', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DON JUAN COIN GALLEGO', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DON LUCIO', 1, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DON PELAYO', 3, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'DON RODRIGO', 1, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'PLAZA', 'DOÑA LOLA', 1, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'DULCINEA', 1, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'DUQUE DE AHUMADA', 1, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'ECCEHOMO', 1, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'ECUADOR', 1, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'EDUARDO IGLESIAS PEREZ', 11, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'URB', 'EL JARDIN', 11, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'URB', 'EL LIMONAR', 1, 300);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'EL QUIJOTE', 3, 22);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'EL ROMERAL', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'CALLE', 'EL TORO', 2, 40);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'CALLE', 'EL VISILLO', 1, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'ELOY TELLEZ', 1, 25);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CAMINO', 'ENMEDIO', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'ENRIQUE ATENCIA PORTILLO', 1, 21);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'ENRIQUE VAN DULKEN', 2, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'ENRIQUE VAN DULKEN', 14, 21);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'PLAZA', 'ESLORA', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ESMERALDA', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'ESPERANZA', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'ESPINAR', 1, 22);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (23, 'PLAZA', 'ESTACION', 2, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'ESTACION', 1, 22);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'ESTE', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'ESTRELLA', 1, 18);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'EUGENIO MORALES JURADO', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'EUGENIO MORALES JURADO', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'EXPLANADA DE LA ESTACION', 20, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'FALUCHA', 1, 60);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'FARO NUEVO', 1, 15);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'FEDERICO DIEZ', 1, 13);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'FEDERICO MACIAS', 2, 23);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'FEDERICO MACIAS', 3, 21);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'FEDERICO TELLEZ MACIAS', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'FEDERICO TERRON RGEZ.', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'FEDERICO VAHEY', 6, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'FELIPE EL HERMOSO', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'FELIPE II', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'FELIX RGUEZ DE LA FUENTE', 2, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'FERNANDO III', 1, 99);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'FERNANDO VIVAR', 99, 99);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'FERROCARRIL', 2, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'FINCA BATERIA', 5, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'FOMENTO', 5, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'FORJADOR', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'FORTALEZA', 1, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'FORTALEZA ALTA', 1, 26);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'FRAGUA', 1, 26);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (4, 'CALLE', 'FRANCISCO DE GOYA', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'FRANCISCO JIMENEZ PUERTA', 1, 199);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'FRANCISCO LABAO GAMEZ', 1, 99);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'FRANCISCO PALMA ARCAS', 7, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'FRAY JULIAN MARCOS', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'FRAY RAFAEL DE VELEZ', 1, 4);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'FRESCA', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'GABARRA', 2, 147);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'GAMBA', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'GARCIA DEL OLMO', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'PASO', 'GITANILLO DE VELEZ', 1, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'GLORIA', 1, 75);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'GLORIA', 1, 82);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'GLORIA', 77, 107);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'PLAZA', 'GLORIA', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'GRANADA', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'GREMIOS', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'GROSELLA', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'GRUPO MANUEL DEL VALLE', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'GUAYABA', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'GUIRADO', 1, 4);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'GUZMAN EL BUENO', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'HACHEROS', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'HACILLA', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'HERMANOS FDEZ LUPIAÑEZ', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'HERMANOS LABAO', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'HERMANOS LOPEZ CAMPOS', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'HERMANOS PINZONES', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'HERREROS', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'HIERBA DE SAN JUAN', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'HIERBA LUISA', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'HIERBABUENA', 1, 41);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'HISPANIDAD', 1, 41);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'HISPANIDAD', 20, 41);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'HISPANIDAD', 41, 41);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'HOJALATEROS', 31, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'HORNO ARABE', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'AVDA', 'HORNO MONJAS CALLEJON', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'HUEVA', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'HUERTA CASILDA', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'HUERTA CASILDA', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'HUERTO CARRION', 1, 27);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'HUERTO CARRION', 2, 24);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'HUERTO CARRION', 26, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'HUERTO CARRION PROLONG.', 1, 45);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'HUERTO DE LOS TARDIOS', 1, 15);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'HUERTO DEL VICARIO', 1, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'HUERTO DEL VICARIO CION', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'HUERTO DEL VICARIO RINCON', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'IGNACIO ZULOAGA', 1, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'IGUALADA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'AVDA', 'IMAGINERO SANCHEZ MESA', 1, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'INFANTA ELENA', 1, 11);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'INFANTES', 2, 54);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'INFANTES', 29, 33);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'INFANTES', 56, 68);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'INFANTES', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'INSTITUTO', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'INVIERNO', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'ISIDORO RIVAS DIAZ', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'JABEGA', 7, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'PASJE', 'JABEGA', 7, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'JAEN', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'PLAZA', 'JAIMA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'JAIME I', 5, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'PLAZA', 'JARA', 1, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'JARDIN', 20, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'JARDIN EL ROMERAL', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'JARDINES DEL ROCIO', 7, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'JAZMIN', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'JEREZ', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'JESUS EL POBRE', 1, 21);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'JESUS EL RICO', 1, 21);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'JESUS FLORES GONZALEZ', 2, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'JOSE MENDEZ HOYOS', 1, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (4, 'CALLE', 'JOSE MESA RUIZ', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'JOSE RIVERA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'JOSE RUIZ RUIZ', 5, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'JOSE TELLEZ MACIAS', 5, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'PASAJE', 'JOYEROS', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'JOYEROS', 3, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'JUAN AGUAYO MORENO', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'JUAN AGUAYO MORENO', 30, 30);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'JUAN AGUAYO MORENO', 35, 35);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'JUAN AGUAYO MORENO', 60, 60);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'JUAN BAUTISTA HURTADO', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'CALLE', 'JUAN BREVA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'JUAN CARLOS I', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'JUAN CARLOS I', 2, 2);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'JUAN CARLOS I', 30, 50);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'JUAN COIN GALLEGO', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (4, 'CALLE', 'JUAN DE JUANES', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'JUAN FERNANDEZ PALMA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'JUAN GOMEZ JAIME', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'JUAN GRIS', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'CALLE', 'JUAN LISBONA CORNEJO', 169, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'CALLE', 'JUAN LISBONA ZAPATA', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'JUAN PABLO II', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'JUAN SEBASTIAN EL CANO PJE.', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'JUAN VAZQUEZ RENGIFO', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'CALLE', 'JUEVES SANTO', 1, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'JULIO ROMERO DE TORRES', 1, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'JUMILLA', 3, 69);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'JUNQUERA', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'CALLE', 'KIWI', 1, 50);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'LA BARRANCA', 1, 27);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'LA CARRERA', 1, 34);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'LA LAGUNA', 1, 23);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'LA LEGION', 1, 18);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'LA NIÑA', 1, 18);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'LA PESETA', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'PASAJE', 'LABRIEGOS', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'LAGO DE SANABRIA', 1, 99);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'LAGUNA CHICA', 66, 69);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'LAGUNA DE CAMPILLOS', 999, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'LAGUNAS DE RUIDERA', 1, 36);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'PASEO', 'LARIOS', 1, 36);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'LAS ARENAS', 1, 83);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (16, 'CALLE', 'LAS MELOSAS', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'SAN ANDRES', 21, 61);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'SAN ANDRES', 26, 80);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'PLAZA', 'SAN ANTONIO DE PADUA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN CAYETANO', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'SAN CRISTOBAL', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN DIEGO', 2, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN ELIAS', 2, 5);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'SAN FRANCISCO', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN GABRIEL', 1, 23);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'SAN ISIDRO', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN JOSE', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN JOSE', 1, 35);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'SAN JOSE DE CALASANZ', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN JUAN', 1, 18);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'SAN JUAN DE DIOS', 2, 22);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN JUAN DE DIOS', 2, 22);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN LUCAS', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN MARCOS', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN MARTIN', 1, 17);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN MATIAS', 1, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN MIGUEL', 4, 18);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'SAN PABLO', 1, 4);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CALLE', 'SAN PEDRO', 1, 10);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CALLE', 'SAN PEDRO DE LA VIÑA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SAN RAFAEL', 2, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CALLE', 'SAN RAFAEL', 36, 36);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CALLE', 'SAN TELMO', 2, 25);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'SANCHO PANZA', 1, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'PLAZA', 'SANTA CRUZ', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'SANTA INES', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'SANTA LUCIA', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SANTA MARGARITA', 8, 27);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SANTA MARIA', 7, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SANTA MARIA MAGDALENA', 2, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SANTA TERESA', 1, 40);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'PASAJE', 'SANTIAGO RUSIÑOL', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SANTA MARIA', 1, 27);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'SANTA MARIA MAGDALENA', 7, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SANTA TERESA', 1, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'SANTIAGO RUSIÑOL', 1, 40);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'SANTIAGO Y SANTA ANA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CALLE', 'SANTO SEPULCRO', 1, 45);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SANTO TOMAS', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SANTUARIO', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SARMIENTO', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'SEÑOR DE LA POLLINICA', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'SEÑOR DEL HUERTO', 3, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CALLE', 'SERAFIN JAIME ALTAMIRA', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CALLE', 'SEVERO OCHOA', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SEVILLA', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (12, 'CALLE', 'SIEMPRE VIVA', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SILLA', 1, 11);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'SOLEA', 1, 11);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (13, 'CALLE', 'SOLEA', 28, 33);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (14, 'PASEO', 'SOLERA', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'SUBIDA DEL CERRO', 2, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'SUBIDA MURALLAS', 1, 13);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'PASAJE', 'SUR', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'SUSPIRO', 1, 18);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'TAJO DE SAN SEBASTIAN', 1, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'TAMARINDO', 1, 50);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'TAPIA DE CRUZ', 1, 34);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'TARAMILLAS', 1, 33);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (5, 'CALLE', 'TEJARES', 1, 27);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'TEJEDA', 1, 27);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'TENERIAS', 1, 27);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'TENIENTE ARMANDO LOPEZ', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'TERCERA CAIDA', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'TIMON', 1, 2);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'PASAJE', 'TIMON', 2, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (22, 'CALLE', 'TOLEDO', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'TOMILLO', 1, 4);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'TORCAL', 1, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'TORIL', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'TORIL', 2, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'TORNO SAN JUAN DE DIOS', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'TRAÑA', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'CALLE', 'TRASCASAS CAPITULARES', 4, 28);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (10, 'PLAZA', 'TRASERA LA GLORIA', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'TRES CASAS', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'TULIPANES', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (3, 'CALLE', 'TUNICA', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'CALLE', 'UTIEL', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'CALLE', 'UTRERA', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'VALLADOLID', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'VALLE DE VIDRIALES', 2, 32);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'VALLE DEL TERA', 1, 14);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (15, 'CALLE', 'VAQUERIA', 5, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (17, 'CALLE', 'VEGA', 2, 24);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (18, 'CALLE', 'VELA', 1, 1);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'CALLE', 'VELAZQUEZ', 1, 50);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'VELESOL', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'VERANO', 2, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'VERDEMAR', 2, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'VERDIALES', 2, 22);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'VICTORIANO RUIZ', 2, 4);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'VIERNES SANTO', 2, 6);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'VILLA DE MADRID', 9, 33);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'CALLE', 'VILLA DE MADRID', 2, 40);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (6, 'CALLE', 'VILLA DE MADRID', 35, 999);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (9, 'CALLE', 'VILLA DE MADRID', 42, 72);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'VILLA LOLA', 1, 16);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'VILLA LOLA', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (20, 'CALLE', 'VILLAS DE VELEZ', 1, 19);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'VILLAVERDE', 2, 11);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'VIÑEROS', 1, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'VIOLETA', 2, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'VIRGEN DE LA AMARGURA', 1, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'VIRGEN DE LA CARIDAD', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (4, 'CALLE', 'VIRGEN DE LAS ANGUSTIAS', 1, 11);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (21, 'CALLE', 'VIRGEN DE LAS SERVITAS', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'VIRGEN DEL CARMEN', 1, 8);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (19, 'CALLE', 'VIRGEN DEL PRADO', 1, 3);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'VIRGEN DEL ROSARIO', 1, 9);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (8, 'CALLE', 'WENCESLAO MORENO', 3, 12);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (1, 'CALLE', 'YECLA', 1, 99);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (7, 'CALLE', 'YEDRA', 1, 20);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (2, 'CALLE', 'YUCAS', 5, 7);
INSERT INTO callejero (seccion, tipo_via, nombre_calle, numero_inicio, numero_fin) VALUES (11, 'AVDA', 'ZALIA', 1, 5);